### PR TITLE
CmdStanPy and PyStan3 support

### PR DESCRIPTION
**Pull request by ahartikainen**
PR adds support CmdStanPy and PyStan3 support.

### CODE REVIEW

**Comment by adamhaber** [comment]
Hi Ari! Thanks a lot for doing this. I've been kind of neglecting this project since I couldn't get conda packaging to work, and I want something users can just install instead of struggling with all the R-base and RPy dependencies...

I'm curious - did installation go smoothly for you?

If you think we can work on packaging this together and bring it to a point where it's actually useful for python and brms users, I'd be more than happy to!

**Comment by ahartikainen** [comment]
Yes, we could check if there is a way to add this package to conda.

I think installation was ok, there was some problem while installing, but reinstall was fine.

I wonder what is minimal brms install (is there a way to do it without rstan?; use cmdstanr?)

**Comment by adamhaber** [comment]
> Yes, we could check if there is a way to add this package to conda.

Awesome! What would be the best way to do this in your opinion?

If we'll be able to get `conda install pybrms` working, next thing is probably more comprehensive testing? Would be happy to take that... 

> I wonder what is minimal brms install (is there a way to do it without rstan?; use cmdstanr?)

Yes, brms supports cmdstanr as a backend.

**Comment by meereeum** [comment]
super minor, but I think the ValueError string has to be changed so braces aren't interpreted as string formatting. should be: `"Unsupported backend {}. Select from {{'cmdstanpy', 'pystan'}}".format(backend)`

**Comment by sreedat** [comment]
Hi All

Are there any instructions I can use to work with CmdStan for ```pybrms``` to work. About a year ago I was actively exchanging notes with @adamhaber on testing and using ```pybrms``` on both Windows and Linux. I succeeded with Windows but not Linux.

My attempts to do so now has failed in both the platforms. Any pointers would be a welcome help @ahartikainen @meereeum @adamhaber

**Comment by ahartikainen** [comment]
Hi, tbh I forgot this PR.

@adamhaber is there a way to activate tests?

**Comment by sreedat** [comment]
@ahartikainen @adamhaber I have now tried to install and test ```pybrms``` in multiple configurations on Windows under Anaconda. What I find strange is that, when I try to run ```pip install pybrms``` it tries to install ```pystan``` also. This is completely messing up the installation process. I have stopped using ```pystan``` on Windows. So this was an unpleasant surprise!

Did the installation requirements for ```pybrms``` change since last year?

**Pull request closed without merging**
